; Chiron's Disk Blaster - Initialization and Configuration File

[User Interface]
options_background_color_r = 0.10
options_background_color_g = 0.18
options_background_color_b = 0.24
options_background_color_a = 1.00

[External Paths]
options_greaseweazle_path = "C:\Program Files\greaseweazle-1.23"
options_ciderpress2cli_path = "C:\Program Files\cp2_1.2.0_win-x64_sc"
options_opencbm_path = "C:\Program Files\opencbm-0.4.99.104\amd64"
options_dd_path = "C:\Program Files\dd-0.6beta3"

[External Executables]
options_greaseweazle_executable = "gw.exe"
options_ciderpress2_cli_executable = "cp2.exe"
options_opencbm_cbmctrl_executable = "cbmctrl.exe"
options_opencbm_d64copy_executable = "d64copy.exe"
options_opencbm_imgcopy_executable = "imgcopy.exe"
options_opencbm_d82copy_executable = "d82copy.exe"
options_dd_executable = "dd.exe"
